// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	AppID          int64
	Name           string
	Categories     []string
	HeaderImageUrl pgtype.Text
	FetchedAt      pgtype.Timestamptz
}

type Gaggle struct {
	ID        pgtype.UUID
	Slug      pgtype.Text
	Name      string
	CreatedBy pgtype.Int8
	CreatedAt pgtype.Timestamptz
}

type GaggleMember struct {
	GaggleID pgtype.UUID
	UserID   int64
	Role     pgtype.Text
	JoinedAt pgtype.Timestamptz
}

type Invite struct {
	ID        string
	GaggleID  pgtype.UUID
	Status    pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Library struct {
	UserID    int64
	AppID     int64
	Playtime  pgtype.Int4
	FetchedAt pgtype.Timestamptz
}

type User struct {
	SteamID     int64
	DisplayName string
	Avatar      pgtype.Text
	Verified    bool
	LastLogin   pgtype.Timestamptz
}

type Wishlist struct {
	UserID    int64
	AppID     int64
	AddedAt   pgtype.Timestamptz
	FetchedAt pgtype.Timestamptz
}
