// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one

SELECT steam_id, display_name, avatar, verified, last_login FROM users WHERE steam_id = $1
`

func (q *Queries) GetUser(ctx context.Context, steamID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, steamID)
	var i User
	err := row.Scan(
		&i.SteamID,
		&i.DisplayName,
		&i.Avatar,
		&i.Verified,
		&i.LastLogin,
	)
	return i, err
}
